### ISSUE TITLE
Gnome shortcut for 'Show the Notification List' doesn't work when the top bar is hidden.

### ISSUE THREAD

**Issue by govarthenan** [mlutfy/hidetopbar#327] opened 2021-12-02 13:49 UTC
I turned off the extension and tried the shortcut (Super + V), which works except when an app is running on fullscreen mode. When I turn on the extension again, and the shortcut didn't work in either of the situations. No other problems regarding shortcuts so far.

**Comment by tuxor1337** [comment] 2022-01-23 08:29
Duplicate of #228

**Closed** 2022-01-23 08:29 UTC
Labels: duplicate, compatibility
