### ISSUE TITLE
Hide the top bar when showing a notification

### ISSUE THREAD

**Issue by TuzelKO** [mlutfy/hidetopbar#326] opened 2021-11-18 09:45 UTC
When a notification is displayed, the top bar is minimized until the notification disappears from the screen. The game with the settings did not manage to solve this problem. 

![изображение](https://user-images.githubusercontent.com/38176435/142391003-a8e21538-5198-4138-a7de-9d3f484caff0.png)
![изображение](https://user-images.githubusercontent.com/38176435/142391033-68ab6fb4-96ac-43f4-b4fb-a21ee1d18f1b.png)

Manjaro Linux / Gnome 40.4.0 / Extension last version from extensions.gnome.org

**Comment by tuxor1337** [comment] 2021-11-18 18:14
Duplicate of #275.

Use the following extension to move the notification pop-ups to a position where they don't overlap with the top bar:  https://extensions.gnome.org/extension/708/panel-osd/

**Closed by tuxor1337** 2021-11-18 18:14 UTC
