### ISSUE TITLE
Module is not loading

### ISSUE THREAD

**Issue by mhoangvslev** [mlutfy/hidetopbar#307] opened 2021-09-14 18:43 UTC
```GLib.FileError: Failed to open file “/home/minhhoangdang/.local/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/schemas/gschemas.compiled”: open() failed: No such file or directory"```

It seems like you forgot to compile before shipping.

**Comment by tuxor1337** [comment] 2021-09-14 19:03
How did you install? The file is in the version shipped via extensions.gnome.org (direct download link so you can check yourself: https://extensions.gnome.org/extension-data/hidetopbarmathieu.bidon.ca.v96.shell-extension.zip).

**Comment by mhoangvslev** [comment] 2021-09-14 19:05
I installed it through gnome-extension through chrome. The extension app reports the above error. What I did is delete the repo, clone the latest commit and compile. The missing file appears afterward and it works after refreshing the shell.

**Comment by tuxor1337** [comment] 2021-09-14 20:01
Since it's working for you and it's unclear how to reproduce the problem, I'm closing this.

**Closed by tuxor1337** 2021-09-14 20:01 UTC
Labels: unconfirmed
