### ISSUE TITLE
Extension dont work after last update (23 Jan)

### ISSUE THREAD

**Issue by iiamalex** [mlutfy/hidetopbar#335] opened 2022-01-25 11:24 UTC
The extension don't work anymore after the last update.
Gnome version: 3.36.7
Hide Top Bar Version: 100

**Comment by coldtobi** [comment] 2022-01-25 13:05
If you are using a Debian based distribution, the preferred installation method is to use the packaged version. By this, compatibility problems caused by different gnome-shell versions in your distribution can be avoided. You can install the package with:

`sudo apt install gnome-shell-extension-autohidetopbar`

**Comment by tuxor1337** [comment] 2022-01-25 18:25
@coldtobi Thanks for untiringly mentioning this point, it is really very useful! :)

@iiamalex You write that you are using version 100, which is from November 2021. Since you are on GNOME 3.36, this is the latest version for your system and you shouldn't have received an update recently. However, my guess is that you might have been affected by the problem with version 101 (#332) that is not compatible with your version of GNOME and which is not available any more from extensions.gnome.org. So you should downgrade to version 100 and restart the GNOME shell (e.g. log off and on again).

Closing as duplicate of #332

**Closed by tuxor1337** 2022-01-25 18:25 UTC
