### ISSUE TITLE
top bar & dash bar overlap when both visible

### ISSUE THREAD

**Issue by donington** [mlutfy/hidetopbar#191] opened 2019-10-07 02:32 UTC
I'm pretty new to gnome3, but would there be a way to make the top x corner of the dash bar (x as in left or right) align to the bottom x (again left or right) of the top bar? This would prevent the overlap when both are visible.

**Comment by tuxor1337** [comment] 2019-10-07 06:11
Duplicate of https://github.com/mlutfy/hidetopbar/issues/149

**Closed by tuxor1337** 2019-10-07 06:11 UTC
