### ISSUE TITLE
Upgrade to Gnome 3.21 ?

### ISSUE THREAD

**Issue by iago-lito** [mlutfy/hidetopbar#108] opened 2016-09-15 09:37 UTC
Hey, my shell switched to 3.21 after an unfortunate `dist-upgrade`.. and the extension seems no longer to work :(

I have naively tried to edit `metadata.json` to match the new version number and install it manually, but it did not work.

Does it mean it'll be not trivial to upgrade ?

**Comment by tuxor1337** [comment] 2016-09-15 10:57
Since 3.21 is unstable, it won't be supported officially by hidetopbar. Still, it has already been confirmed by some users that hidetopbar does work fine under 3.21.91 just by adding that version number to metadata.json, see #107

**Closed by tuxor1337** 2016-09-15 10:57 UTC
Labels: duplicate, enhancement
