### ISSUE TITLE
redeclaration of let settings_vbox

### ISSUE THREAD

**Issue by mnwstl** [mlutfy/hidetopbar#129] opened 2017-04-08 07:29 UTC
Hello! I do not know what this is:
(ubuntu-gnome 17.04 / gnome 3.24)
![2017-04-08 04-36-47](https://cloud.githubusercontent.com/assets/22776404/24826841/3b7a1dcc-1c15-11e7-9624-0d98bf188ad0.png)

TypeError: redeclaration of let settings_vbox

Stack trace:
  Application<._getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:74:13
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:89:31
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  Application<._onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
  wrapper@resource:///org/gnome/gjs/modules/lang.js:178:22
  main@resource:///org/gnome/shell/extensionPrefs/main.js:399:5
  @<main>:1:49

**Comment by tuxor1337** [comment] 2017-04-08 07:48
Obviously a duplicate of #128

**Closed by tuxor1337** 2017-04-08 07:48 UTC
