### ISSUE TITLE
Notifications make the topbar hide itself

### ISSUE THREAD

**Issue by rrnetopantoja** [mlutfy/hidetopbar#348] opened 2022-03-17 03:47 UTC
I've setted the extension for just hide when there is a active window overlapping the topbar.

Nonetheless, it hides itself every time I receive a notification. And I've searched, but didn't find any option in the extension settings to change it. I think it is an issue.

**Comment by tuxor1337** [comment] 2022-03-17 06:02
[](https://github.com/mlutfy/hidetopbar/issues/326#issuecomment-973131378)Duplicate of https://github.com/mlutfy/hidetopbar/issues/275.

Use the following extension to move the notification pop-ups to a position where they don't overlap with the top bar: https://extensions.gnome.org/extension/708/panel-osd/

**Closed by tuxor1337** 2022-03-17 06:02 UTC

**Comment by rrnetopantoja** [comment] 2022-03-31 00:15
@tuxor1337 sorry for keep insisting, but the extension that you recommended isn't avaible for Gnome 41. I am using it in the moment.

![Captura de tela de 2022-03-30 20-14-48](https://user-images.githubusercontent.com/38327530/160951243-4d3580e7-3a92-40f3-b2e0-4dd5725e5530.png)

**Comment by coldtobi** [comment] 2022-03-31 04:36
@rrnetopantoja  https://gitlab.com/jenslody/gnome-shell-extension-panel-osd/-/merge_requests/32 might help you. At least someone commented "works with Gnome 41".
