### ISSUE TITLE
Locking screen makes top bar goes hidden forever even in overview

### ISSUE THREAD

**Issue by ptitjes** [mlutfy/hidetopbar#58] opened 2015-02-18 15:21 UTC
When you lock the screen and come back, the top bar is definitly gone. It does not show in overview.

Restarting shell makes the top bar visible again in overview.

Gnome Shell: 3.14.3-0ubuntu1~utopic1

Hide Top Bar configuration:
animation-time-overview=0,20000000000000003886
hot-corner=true
mouse-sensitive=true
mouse-triggers-overview=false

**Comment by tuxor1337** [comment] 2015-02-18 16:11
I can't reproduce this using the same settings that you posted. I'm also on 3.14.3, but using Fedora 21. Do you have a multi-monitor setup? Are there any other extensions that you use in parallel?

**Comment by ptitjes** [comment] 2015-02-18 16:47
Indeed, I use user themes, clipboard indicator and one or two others. I'll try tomorrow to reproduce this without any other extensions and I keep you posted.
Thanks for your fast reaction.

**Comment by ptitjes** [comment] 2015-02-19 08:46
Ok. I narrowed it down:
Every extensions off except hidetopbar (so no theme)

1) Configure hidetopbar with mouse-sensitive=true
2) Open a window that can be resized (say thunderbird) and make it fullscreen with Meta-UpArrow
3) Top bar disappears as expected
4) Move the mouse to the top screen edge as to make top bar appear and select the "Lock Screen" button in the right menu
5) Come back from locked screen by typing your code (notice top bar is already gone for good)
6) When back in shell move mouse to top edge or press Meta to go to the overview and notice top bar is gone

Ask me if you need more info

**Comment by tuxor1337** [comment] 2015-02-19 09:37
I can confirm that the top bar is hidden on the (un-)lock screen which is certainly no intended behaviour. But for me the top bar always reappears after login. So marking this as bug, since there's something wrong with the lockscreen behaviour.

**Comment by jcuenod** [comment] 2015-04-01 12:41
I can confirm this issue as well. I'm on FC21 but with me the bar does not reappear after login.

**Comment by ngrennan-inflection** [comment] 2015-04-23 16:56
I did not have this issue on Fedora 21, but I do now with Gnome 3.16 on Fedora 22 beta.

**Comment by derekchiang** [comment] 2015-05-07 09:32
Can confirm that this issue exists on Ubuntu 15.04 with Gnome 3.14.4.  Suspension also makes the top bar disappear.

**Closed** 2015-05-07 10:38 UTC
Labels: bug

**Comment by ngrennan-inflection** [comment] 2015-05-13 18:52
The fix works for me. :)
