### ISSUE TITLE
Bar hides if a notification pop-up appears

### ISSUE THREAD

**Issue by kyteinsky** [mlutfy/hidetopbar#297] opened 2021-09-02 10:50 UTC
I have set top bar to hide only when a window takes its place. Everything works perfect, thanks for that.
But when a notification pops up when the bar is visible, it hides itself and shows back as soon as notification goes away.

Distro: Manjaro 21

**Comment by tuxor1337** [comment] 2021-09-02 11:40
Duplicate of #275.

Use the following extension to move the notification pop-ups to a position where they don't overlap with the top bar:  https://extensions.gnome.org/extension/708/panel-osd/

**Closed by tuxor1337** 2021-09-02 11:40 UTC

**Comment by kyteinsky** [comment] 2021-09-02 13:16
I have used Panel OSD before and is a great extension, but my concern is with the behaviour of this extension of how it treats the pop up when the bar (panel) is already showing on the screen. See the video attached for reference. If fixing this would take too much time and is just a minor issue, please ignore this issue.

https://user-images.githubusercontent.com/20724224/131849985-e3f7f356-1fa9-4a38-8585-23e4a08074a9.mp4

Thanks

**Comment by tuxor1337** [comment] 2021-09-02 16:24
As I said, this has been discussed in #275 already:
> If the notifications don't hide the bar, the bar will overlap the notifications and you couldn't read them. I think, you don't really want this extension to change, but you want the notifications to show up in a different position (e.g. a few pixels down) where it won't overlap with the top bar. I don't want to implement moving the notifications as part of this extension because that's rather a different kind of functionality. This extension only fiddles with the panel and doesn't touch any other elements of the GNOME UI.

**Comment by kyteinsky** [comment] 2021-09-02 16:29
Yeah I read that entire thread, you don't want to fiddle with the position of the notification. I think there is a disconnect between us. 
Never mind, thanks for your time.
