### ISSUE TITLE
Bloking to switch between windows in Firefox

### ISSUE THREAD

**Issue by FlorianMilcendeau** [mlutfy/hidetopbar#254] opened 2020-09-26 07:04 UTC
When I want to switch between windows in Firefox, switching between windows gets stuck, I have to hover over the dash-to-dock or top bar then it unlocks

**Comment by tuxor1337** [comment] 2020-09-26 07:19
1. Do you mean "tabs" when you write "windows"? Then it might be related to this one: https://github.com/mlutfy/hidetopbar/issues/212
2. Is this only when Dash-to-dock is active? Would you please try to reproduce the issue without dash-to-dock?
3. Can you reproduce this issue when the Firefox window is NOT maximized?

**Comment by FlorianMilcendeau** [comment] 2020-09-26 07:49
1. Yes I meant "tabs" sorry for my english ^^
2. No even when it's not active
3. No that when it's maximized
Gnome 3.36.3 wayland,
![Capture d’écran de 2020-09-26 09-47-23](https://user-images.githubusercontent.com/59692433/94335691-899f5f80-ffdd-11ea-812f-88b35790f148.png)

**Comment by tuxor1337** [comment] 2020-09-26 07:55
I'm closing this as a duplicate of #212 then.

**Closed by tuxor1337** 2020-09-26 07:55 UTC
Labels: compatibility
