### ISSUE TITLE
Launcher icon covered by top panel

### ISSUE THREAD

**Issue by SMacK72** [mlutfy/hidetopbar#343] opened 2022-02-21 15:01 UTC
When I have the dock on either the left or the right and enable Hide Top Bar, it moves the icons up and thus the first icon is covered by the top bar.

This is when the extension is off, the dock/icon are in the correct position.

![Screenshot from 2022-02-21 09-48-05](https://user-images.githubusercontent.com/89423077/154978897-25099853-263b-470b-be74-0c89687254a3.png)

When the extension is active, the icons in the dock move up and are then covered by the top panel.

![Screenshot from 2022-02-21 09-50-00](https://user-images.githubusercontent.com/89423077/154979202-3a586cba-0cbd-4407-8b74-12a23120e1aa.png)

System:

![Screenshot from 2022-02-21 09-57-07](https://user-images.githubusercontent.com/89423077/154979944-46aa51d7-d4ac-4c56-8749-3561f7b38c0d.png)

I've searched extensively for a answer but have found nothing concern this issue. Any thoughts would be greatly appreciated. Thanks.

**Comment by tuxor1337** [comment] 2022-02-21 15:14
Closing as duplicate of #149 (I also pinned that issue so it can be found more easily)

**Closed by tuxor1337** 2022-02-21 15:14 UTC
