### ISSUE TITLE
Support window-list shell extension?

### ISSUE THREAD

**Issue by phipolis** [mlutfy/hidetopbar#99] opened 2016-04-21 17:09 UTC
Loving hidetopbar, and wishing it also supported the [window-list](https://extensions.gnome.org/extension/602/window-list/) Gnome classic mode shell extension. 

Would it be feasible to add a "also hide window-list if enabled" toggle to hidetopbar? Or is that something better placed in a fork?

**Comment by tuxor1337** [comment] 2016-04-26 06:52
This is a duplicate of #23

**Closed by tuxor1337** 2016-04-26 06:52 UTC
Labels: enhancement, wontfix
