### ISSUE TITLE
dconf warning when enabling hidetopbar

### ISSUE THREAD

**Issue by gzliudan** [mlutfy/hidetopbar#98] opened 2016-04-11 02:48 UTC
#83 
I also encounter this problem：

[test@master56 hidetopbar@mathieu.bidon.ca]$ gnome-shell-extension-tool -e hidetopbar@mathieu.bidon.ca
'hidetopbar@mathieu.bidon.ca' is now enabled.

(process:4511): dconf-WARNING **: failed to commit changes to dconf: Error spawning command line 'dbus-launch --autolaunch=2a25722518174e678ad5cfcad2655e70 --binary-syntax --close-stderr': Child process exited with code 1

BTW: How to hide bottom bar of centos 7.x for a specified user?

**Comment by tuxor1337** [comment] 2016-04-12 05:42
Which version of gnome and which OS are you using? Furthermore, are there any other extensions you are using in parallel?

**Comment by tuxor1337** [comment] 2016-08-20 07:51
Closing this because it works for me (I can't reproduce this).

**Closed by tuxor1337** 2016-08-20 07:51 UTC
Labels: unconfirmed
