### ISSUE TITLE
Show panel on key focus (via Ctrl+Alt+Tab)

### ISSUE THREAD

**Issue by jclrb** [mlutfy/hidetopbar#81] opened 2015-10-06 18:43 UTC
(Gnome 3.14, Debian Jessie)

Expected behavior:
- Make sure top bar is visible
- Press Ctrl-Alt-Tab  (default for "Switch system controls") and select Top Bar
- Press arrow keys, top bar features are usable with the keyboard.

With hidden top bar:
- Make sure top bar is hidden
- Press Ctrl-Alt-Tab, and select Top Bar
- (Bug) Top Bar remains hidden, when it should become visible
- (Bug) Despite being hidden, arrow keys still let you use the top bar.

(Fixed: wrong keybind)

**Comment by tuxor1337** [comment] 2015-10-06 19:02
Confirmed.

One remark though - the default shortcut for "Switch system controls" is Ctrl-Alt-Tab, according to this manual page: https://help.gnome.org/users/gnome-help/stable/keyboard-shortcuts-set.html.en

**Comment by tuxor1337** [comment] 2015-12-03 02:48
Just some remarks on this: When the top bar gets the key focus, it's directly passed down to the activity button which is `panel.actor.get_first_child().get_first_child().get_first_child()`. So it's possible to listen to the `key-focus-in` signal of this element. But after that, it's really messy to keep track of the focus. That would mean listening to `key-focus-out` for all children (and children of children etc.) of the panel.

Until there is a more elegant way of doing this, I don't think it's a good idea to fix this.

**Comment by tuxor1337** [comment] 2015-12-04 15:30
@jclrb Would you mind if we completely removed the top panel from "Switch system controls"? If yes, why do you need it?

**Comment by tuxor1337** [comment] 2015-12-04 15:40
There already is a shortcut setting for Hide Top Bar that lets you show the panel by pressing a shortcut. Would it be what you want if I added an option to give the key focus to the panel whenever this shortcut is pressed?

**Comment by tuxor1337** [comment] 2015-12-06 12:49
Closing this because nobody seems to be interested in this feature any more. With the latest commit, the panel has been removed from Ctrl+Alt+Tab anyway.

**Closed by tuxor1337** 2015-12-06 12:49 UTC
Labels: bug

**Comment by jclrb** [comment] 2016-04-10 19:20
Sorry I haven't checked in, I had to use a windows laptop for a while.

Yes giving focus to the top bar when shown would be fantastic for me a keyboard user (I don't use a mouse because of stiffness/pain on my hands). And focus would switch to windows when the top bar is hidden again.

Now I do:
1. <hidetopbar shortcut> to show top bar
2. <switch system controls shortcut> to focus top bar
3. Tab/ Arrow keys/ Space etc to activate the menus I need (wifi/sound/whatever)
4. <switch system controls shortcut> to focus windows
5. <hidetopbar shortcut> to hide the top bar
It's just a bit... slow ;-)

The gnome shortcuts for "show notifications" and "show application menu" function normally even with top bar hidden, so that helps some.
