### ISSUE TITLE
hideTopBar showing error

### ISSUE THREAD

**Issue by Thirstypooch** [mlutfy/hidetopbar#304] opened 2021-09-14 02:08 UTC
Gnome 3.36.8
![hideTopBar](https://user-images.githubusercontent.com/36412057/133182788-e97c53c0-1986-4a1b-b93c-5940122cbcfe.png)

**Comment by tuxor1337** [comment] 2021-09-14 07:10
Either it's a duplicate of #301 and you might need to re-install (from extensions.gnome.org) or you should simply log off and on again.

**Closed by tuxor1337** 2021-09-14 07:10 UTC
