### ISSUE TITLE
GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/Settings-40.ui”: No such file or directory

### ISSUE THREAD

**Issue by tribbloid** [mlutfy/hidetopbar#346] opened 2022-03-05 03:15 UTC
This error is encountered when trying to configure it under PopOS 21.10, Gnome 40.5

The settings of extension hidetopbar@mathieu.bidon.ca had an error:

```
GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/Settings-40.ui”: No such file or directory
```

Stack trace:
```
buildPrefsWidget@/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/prefs.js:44:13
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

I wonder if it can be fixed by reinstalling

**Comment by tuxor1337** [comment] 2022-03-05 17:50
Closing as duplicate of #320

**Closed by tuxor1337** 2022-03-05 17:50 UTC
