### ISSUE TITLE
Top toolbar of ALL windows disappears and made my RHEL7.3 unworkable!

### ISSUE THREAD

**Issue by qwertbuddy** [mlutfy/hidetopbar#127] opened 2017-02-13 19:47 UTC
Please let me know a way to undo this, I followed the instructions in your file and cannot use my rhel7.3 properly anymore! Top panel did go away, but so did browser URL address bar of Firefox and I cannot type anything in my Terminal! Also, none of the windows are responsive, i.e after clicking on them I cannot switch focus to them. Need to remove this 'hidetopbar' ASAP. Please advice.
Update: Powering off and powering on my PC again helped kill it. Even soft boot was not working so had to do this manually.

**Comment by tuxor1337** [comment] 2017-02-13 20:02
Press Alt+F2 and type in "gnome-tweak-tool".

**Comment by Wkee** [comment] 2017-03-14 18:25
Go in your safe mode by hitting SHIFT key or ESC. (If you have duel-system, just go and select safemode), select networking , then drop to root prompt. Then run following commands.
`
sudo apt-get remove plymouth
sudo apt-get remove xserver-xorg-video-intel`

Now, reboot,

When you reboot, still you may get black or purple screen,

Press Ctrl+Alt+F1 and login with your username and password.

Then run following commands.

GDM ie Gnome display manager was also causing problems for me, so following step was essential for me

switch to lightdm from gdm3 as display manager.

`sudo apt-get install lightdm
sudo dpkg-reconfigure lightdm`
When you are prompted, select default display manager as lightdm

Now I was back with desktop , without dash or unity but only icons and wallpaper. now run this.

`sudo apt-get install ubuntu-desktop`
Now, reboot after this.

The desktop is back!

now, you can install intel graphic drivers again,

`sudo apt-get install xserver-xorg-video-intel`

**Comment by tuxor1337** [comment] 2017-08-29 14:09
Since this seems to be a question and not a bug report, I'm closing this.

**Closed by tuxor1337** 2017-08-29 14:09 UTC
Labels: question, wontfix
