### ISSUE TITLE
Top bar clock overlaps with overview search box

### ISSUE THREAD

**Issue by PHLAK** [mlutfy/hidetopbar#305] opened 2021-09-14 05:16 UTC
When the top bar is visible and the overview is opened the top bar remains on the screen and the clock overlaps with the search box. See the screenshot below.

![image](https://user-images.githubusercontent.com/53531/133198163-e09b25dd-73bf-4d1b-8967-692774871433.png)

This only seems to be an issue when opening the overview when the top bar is NOT hidden. If the top bar is already hidden then it remains hidden when the overview is opened.

https://user-images.githubusercontent.com/53531/133198624-f42a3adb-20af-4590-8e7b-190c7b4b1e1c.mp4

I see two possible solutions. 1) Hide the top bar when the overview opens or 2) add some padding to the top of the overview to prevent it from overlapping. Personally I'd prefer option 2 but I'll leave that decision up to others.

---

Hide Top Bar v93
Arch Linux
Gnome 40.4
Resolution: 3840 ×2400 (16:10)

**Comment by tuxor1337** [comment] 2021-09-14 07:11
Duplicate of #283, which is fixed by #299

**Closed by tuxor1337** 2021-09-14 07:11 UTC
