### ISSUE TITLE
Freeze with firefox wayland

### ISSUE THREAD

**Issue by Erwyn** [mlutfy/hidetopbar#180] opened 2019-05-04 16:02 UTC
Hi there.

I'm on Fedora 30 with Wayland. It was working perfectly on Fedora 29 but now, when I fullscreen Firefox I get some lags or freezes of Firefox. Meaning: when I switch tab it regularly does not, freezes, but if I just make the topbar reappear it un-freezes Firefox.

Please note that this looks more like some sort of "refresh" issue, I bet Firefox actually changed tab.

**Comment by GuillermoCallaghan** [comment] 2019-05-18 22:56
+1 I have the same issue, in one machine with Fedora 29 it works fine, on the other with Fedora 30 it freezes Firefox.

**Comment by Erwyn** [comment] 2019-05-19 13:31
Hello @GuillermoCallaghan . Thanks for reporting the same issue.

I've noticed on my side that Firefox nightly does not seem to encounter this issue. Could you confirm this by running Firefox nightly on your machine ?

**Comment by GuillermoCallaghan** [comment] 2019-05-19 19:27
Hi @Erwyn,
I tried **Firefox  Nightly** `68.0a1 (2019-05-19) (64-bit)` and it improves a little bit but keeps happening.
Thanks.

**Comment by Erwyn** [comment] 2019-05-20 07:30
Hello @GuillermoCallaghan,

Thank you for the feedback!

**Comment by dwma** [comment] 2019-06-01 00:02
Same problem happens to me too using Firefox 67.0 and Gnome 3.32.2. It doesn't matter whether Firefox is using software or hardware rendering. Anything such as the dock sliding in or a context menu popping up will 'unfreeze' it.

**Comment by texoft** [comment] 2019-06-28 13:47
Hi, I was experiencing this problem too while I was running gnome wayland session, but firefox was running under Xwayland, not natively.

Try starting firefox like this:
`GDK_BACKEND=wayland firefox`
and see if your firefox is running wayland natively (https://www.howto-connect.com/enable-wayland-support-firefox/).

**Comment by GuillermoCallaghan** [comment] 2019-06-28 16:50
Hi @texoft it works fine when I do that.

**Comment by tuxor1337** [comment] 2019-06-28 22:03
@Erwyn Does the suggestion by @texoft solve the issue for you?

**Comment by Erwyn** [comment] 2019-06-29 11:04
@tuxor1337 Confirmed, I added the `MOZ_ENABLE_WAYLAND=1; export MOZ_ENABLE_WAYLAND` and it works seamlessly now.

thanks @texoft  !

**Comment by Erwyn** [comment] 2019-06-29 11:04
Should I close the issue ?

**Comment by tuxor1337** [comment] 2019-06-29 11:13
Okay, I added a note about this to the extensions.gnome.org page. Closing as upstream, since it seems to be (at least in part) caused by Firefox.

**Closed by tuxor1337** 2019-06-29 11:13 UTC
Labels: compatibility, wayland

**Comment by texoft** [comment] 2019-06-30 14:07
You're welcome. Btw. this same problem also seems to happen with Inkscape.

**Comment by vinliao** [comment] 2019-10-09 10:15
@tuxor1337's solution doesn't doesn't work for me, firefox keeps on freezing when changing tab after I've added `MOZ_ENABLE_WAYLAND=1; export MOZ_ENABLE_WAYLAND` on my .bashrc and rebooted. 

I solved this issue by using firefox-wayland which can be be installed through the fedora package manager (`dnf install firefox-wayland`). When opening the firefox, make sure to open the wayland version.
