### ISSUE TITLE
Sometimes stops working on dual screens

### ISSUE THREAD

**Issue by paddelboot** [mlutfy/hidetopbar#253] opened 2020-09-22 14:06 UTC
When switching around primary displays and moving windows from one screen to another, sometimes the top bar freezes and just stays visible, even when it should hide for maximized windows. Using the keyboard shortcut for hide/display does not work either in that case. I then have to deactivate/activate the extension for it to work properly again.

Would be nice if this could be looked into.

Thanks, Paddelboot

Settings (in German):

![image](https://user-images.githubusercontent.com/632353/93894187-be19cf80-fcee-11ea-9c11-98ad6869d4fb.png)

Ubuntu 20.04
HTB v77
Dual screen setup with WQHD and FullHd screens.

Other Gnome extenstions:
- Screenshot Tool v48 (https://github.com/OttoAllmendinger/gnome-shell-screenshot/)

**Comment by tuxor1337** [comment] 2020-09-22 14:29
There are already too many open issues for multi-monitor. I'm pretty sure that this is a duplicate of one of those: https://github.com/mlutfy/hidetopbar/issues/182 https://github.com/mlutfy/hidetopbar/issues/136 https://github.com/mlutfy/hidetopbar/issues/154

**Closed by tuxor1337** 2020-09-22 14:29 UTC

**Comment by paddelboot** [comment] 2020-09-29 15:45
I realized this bug happens when I switch the primary display from one monitor to the other in display settings. Maybe that helps.
