### ISSUE TITLE
Auto-hide broken after using firefox in fullscreen

### ISSUE THREAD

**Issue by adipginting** [mlutfy/hidetopbar#188] opened 2019-09-01 20:56 UTC
The top bar did not appear while hovering mouse over the top of the screen after a fully maximized Firefox window was on opened for several hours. Below is the demonstration.
![top-bar-optim](https://user-images.githubusercontent.com/6162184/64082074-b37f4780-cd33-11e9-9bb3-8affa74b3548.gif)

If after that I open VLC video player fully maximized, the top bar appears when hovering the mouse on the top of the screen.

My computer specifications are below.
1. Ubuntu 18.04.3
2. GNOME Shell 3.28.4
3. Nvidia driver 390.129 on GeForce GT 540M

**Comment by yoyoma2** [comment] 2020-02-25 01:32
Steps:
1) Open firefox with youtube and a second tab
2) Drag the youtube tab out so you have two single tab windows
3) Maximize the youtube window with window manager
4) Play a long video and press F or click fullscreen in bottom right
5) Move mouse to top immediately and lower mouse (bar appears then disappears)
6) Wait 10s or more and repeat step 5 (bar no longer appears)
7) Press f to leave fullscreen and repeat step 5 (bar no longer appears)
8) Unmaximize youtube tab and drag it back to original firefox window
9) Repeat steps 2 onward to observe bug appear/disappear repeatedly

Note: If video stops playing the bug won't occur.

Tested on up to date ubuntu 18.04 LTS

**Comment by yoyoma2** [comment] 2020-03-01 16:09
Another website, [gfycat](https://gfycat.com/advancedhandsomedarklingbeetle-germanshepherdonline-gsdofinstagram), that has a fullscreen mode causes the issue with a maximized firefox.
1) in maximized firefox visit [gfycat](https://gfycat.com/advancedhandsomedarklingbeetle-germanshepherdonline-gsdofinstagram)
2) play the animated gif and click the player's fullscreen button
3) Click their player's _Exit fullscreen_ button after playing 10s or more

Result: The top bar no longer appears when approached (**the auto-hide Dock no longer appears either**)

Interesting observations:
1) hovering over the back button brings up a tooltip and the top bar.  It's as if the earlier failed attempt at making the top bar appear was actually successful but firefox was on top of it.
2) an onscreen keyboard like onboard (while visible) also makes the top bar and auto-hide dock appear normally
3) in firefox's customize dialog, toggling the "Title bar" checkbox (twice if you wish to keep your setting) restores firefox's window to a normal state (like dragging all tabs to a new window did in an earlier comment)
4) In step 3 in the replication steps above, clicking their player's _Exit fullscreen_ button quick enough while firefox's small warning window about fullscreen is still visible, avoids the problem
5) Even if firefox wasn't maximized in step 1, and the the gfycat tab is subsequently closed, the next time firefox is maximized, the top bar and dock won't unhide anymore.
6) Of course disabling the hidetopbar extension avoids the problem entirely including.

Conclusion:
Hide top bar extension doesn't play well with maximized firefox and websites that have a fullscreen mode.  **The standard dock is also affected** if in auto-hide mode.

This bug title should be probably be altered given the more detailed replication steps.

**Comment by yoyoma2** [comment] 2020-05-10 21:05
Was surprised to still see the "unconfirmed" label on this issue. Turns out you need the dock auto-hide to be turned on for the steps to work. Will edit the steps...

**Comment by aunetx** [comment] 2020-05-28 18:18
I have a similar issue: when watching Netflix on my second monitor (with the laptop monitor being switched off), if I put the window in full screen, then approach the mouse to the topbar, the topbar shows as usual.
However, it does not hide automatically any more, and to hide it I need to get out of fullscreen and in again.

**Comment by yoyoma2** [comment] 2020-05-29 01:17
That's interesting aunetx, I'm also using an external monitor on a laptop with the laptop screen being switched off. In the "interesting observations" 1 & 3 above, the top bar does reappear with the mouse pointer being outside the top bar. Moving the mouse pointer into then out of the top bar makes it auto-hide again.

I'm using a website's full screen mode, not firefox's F11 full screen mode.

**Comment by imaginethatok** [comment] 2020-10-23 16:00
I believe I have a related issue. Ubuntu 20.10, Gnome 3.38.1. Thinkpad X1 Carbon 7th (Intel UHD Graphics 620). I'm running Firefox without the title bar. 

Maximizing is fine (hides the top bar as expected), but then moving to the top edge displays the top bar only for a brief period (variable, though typically far less than a second) before it disappears.

**Comment by adipginting** [comment] 2020-10-29 03:08
I don't this issue anymore using the latest version of no topbar. I'm closing this issue.

**Closed** 2020-10-29 03:08 UTC
Labels: compatibility, unconfirmed
