### ISSUE TITLE
Mouse can't move up past top bar if another monitor is set up above it

### ISSUE THREAD

**Issue by nforceroh** [mlutfy/hidetopbar#292] opened 2021-07-21 19:02 UTC
The mouse cursor just hits the top and can't move across to the monitor above it if "Show panel when mouse approaches edge of screen". when the settings is off you can move above it. I would expect the behavior to be when on, that if I move the move to the top edge of the monitor, the top bar appears but once I'm on the above monitor, the bar disappears, not to be completely blocked

**Comment by tuxor1337** [comment] 2021-07-21 19:13
Closing as a duplicate of #174

**Closed by tuxor1337** 2021-07-21 19:13 UTC
Labels: duplicate
