### ISSUE TITLE
Cannot show panel with an absolute pointer

### ISSUE THREAD

**Issue by UlyssesZh** [mlutfy/hidetopbar#370] opened 2022-07-06 19:15 UTC
With an absolute pointer (drawing tablet for example), even if the pressure barrier's threshold is set to 0, the panel cannot be unhidden when I use the absolute pointer to make the mouse cursor approach the top edge.

**Comment by tuxor1337** [comment] 2022-07-24 17:58
Closing as duplicate of #140

**Closed by tuxor1337** 2022-07-24 17:58 UTC
