### ISSUE TITLE
Error after update

### ISSUE THREAD

**Issue by adalibas** [mlutfy/hidetopbar#333] opened 2022-01-23 12:29 UTC
After updating the extension, the extension does not work. (On ubuntu 20.04)

1. Updated the extension via [extensions.gnome](https://extensions.gnome.org/). The extension stopped working.
2. Restarted the computer. The extension still does not work.
3. Uninstalled and re-installed it, restarted the computer extension still does not work.
4. Uninstalled the extension re-installed via ```sudo apt install gnome-shell-extension-autohidetopbar``` restarted the computer the extension does not work.

**Comment by KyleFontenot** [comment] 2022-01-23 14:56
Same here

**Comment by SametSahin10** [comment] 2022-01-23 15:16
Logging off and logging in again fixed the problem for me.

**Comment by adalibas** [comment] 2022-01-23 16:25
After looking more I discovered that there is already a [closed issue](https://github.com/mlutfy/hidetopbar/issues/332) mentioning the problem. It turns out that the extension dropped support for gnome 3.36. I manually installed v.100 of the extension and it works.

Even though, I do not like the decision I completely respect that. It is up to the developers to make such a decision. Thank you for your time. It is a shame that I cannot use any updated version of the extension.

You may close the issue if you want but I have a few suggestions.

1. Do not close the issue so that other people who have the same problem can see that the problem is not going away.
2. Update the gnome.extension page and the github readme so that the users know that the support is dropped for gnome 3.36.
3. Put a disclaimer on the automatic update that the update will break the use for users that have gnome 3.36.

But most importantly

- Consider supporting gnome 3.36 because that is what is used by ubuntu 20.04 which is the current LTS version. The time for the new LTS version may be approaching but this one is going to be around for some time.

**Comment by coldtobi** [comment] 2022-01-23 19:02
>- Consider supporting gnome 3.36 because that is what is used by ubuntu 20.04 which is the current LTS version. The time for the new LTS version may be approaching but this one is going to be around for some time.
>

You should install thr Debian package for your Ubuntu version; this should aalow you to avoid such problems, as those distribution packages can much better consider the (GNOME) versions avsilable and thus better integrate into the system. If it doesn't, report a bug in Ubuntu, this be not a bug for this issue tracker.

(tobi with his Debian package maintainer hat on)

**Comment by tuxor1337** [comment] 2022-01-23 19:36
>     1. Do not close the issue so that other people who have the same problem can see that the problem is not going away.

It's now a pinned issue, so users can directly see it on the GitHub issues front page of this repository.

>     2. Update the gnome.extension page and the github readme so that the users know that the support is dropped for gnome 3.36.

That's 100% transparently included as part of the meta data.

>     3. Put a disclaimer on the automatic update that the update will break the use for users that have gnome 3.36.

It won't any more. It was only for a very short time frame that updates have been breaking the extension for users of 3.36. This is not the case currently.

>     * Consider supporting gnome 3.36 because that is what is used by ubuntu 20.04 which is the current LTS version. The time for the new LTS version may be approaching but this one is going to be around for some time.

Feel free to submit a PR with 3.36 support restored :)

**Comment by tuxor1337** [comment] 2022-01-23 19:37
Closing this as a duplicate of #332

**Closed by tuxor1337** 2022-01-23 19:37 UTC
