### ISSUE TITLE
Problem with dock

### ISSUE THREAD

**Issue by mfilippov** [mlutfy/hidetopbar#165] opened 2018-09-04 08:30 UTC
I have a problem with Dock overlay.
![screenshot from 2018-09-04 11-29-46](https://user-images.githubusercontent.com/927432/45019780-da7a3f00-b035-11e8-91e4-c7ed23f14d24.png)

**Comment by p3732** [comment] 2018-11-08 15:05
Duplicate of #149.

**Closed** 2018-11-24 18:49 UTC
