### ISSUE TITLE
Overview hot corner works one in two times when top bar is hidden

### ISSUE THREAD

**Issue by Magean0** [mlutfy/hidetopbar#222] opened 2020-05-25 19:49 UTC
Hey,

First of all, thanks for your work: I've long been trying to devise a desktop configuration that tucks away all shell components to save space for applications, since full-screen modes are often either non-existent or not convenient. Your extension, combined with the basic Gnome 3's premise of using the Activities overview to do pretty much everything, comes in very handy! However, I still need a way to access the Overview. There's the Super key, but often times I'm too lazy and prefer using the mouse. As a result, the Activities hot corner has become muscle memory for me...

And then I'm getting the following glitch: the hot corner works exactly one in two times when the extension is toggled on. To replicate it, go through those steps:

-disable all extensions but Hide Top Bar (to make sure the problem doesn't come from another extension or a conflict) 
-make sure the Activities hot corner is turned on in both Gnome Tweaks and Hide Top Bar settings
-restart the shell (or log off and on)
-make sure the top bar is actually hidden (for instance, if it's on intelligent hiding, maximize a window). The glitch won't occur when the top bar is shown.
-shove your cursor to the top-left: the hot corner opens the Overview.
-shove it again. Nothing happens.
-repeat a third time: the hot corner works and you exit the overview.
-repeat a fourth time: nothing.

And so on. This is not something I observe when Hide Top Bar is disabled. And as a result, I need to re-train my muscle memory to do two brief mouse-shoving each time I'd like to access or exit the overview.

Mandatory system information:
-Hide Top Bar version 70
-Ubuntu 20.04, using the vanilla gnome-session, not the default Ubuntu session, so that Ubuntu extensions are disabled.
-GNOME Shell 3.36.2
-Display protocol: Xorg
-NVidia proprietary graphics driver

Thanks in advance for having a look.

**Comment by tuxor1337** [comment] 2020-05-26 14:30
Hey, thanks for your report! This seems to be a duplicate of https://github.com/mlutfy/hidetopbar/issues/93

**Closed by tuxor1337** 2020-05-26 14:30 UTC
