### ISSUE TITLE
GNOME 40 [Fedora]: Top bar overlaps with the search bar in the activities overview

### ISSUE THREAD

**Issue by nasseef20** [mlutfy/hidetopbar#293] opened 2021-07-26 17:58 UTC
![Screenshot from 2021-07-26 23-54-55](https://user-images.githubusercontent.com/86907615/127035945-5c2c3e01-9f02-4b56-acc7-2dbaa2e5d40a.png)

I am positive that this extension is causing the problem, as turning this off fixes this overlap problem.

This is the case irrespective of the Shell theme (the shell theme is set to the default anyway).

**Comment by tuxor1337** [comment] 2021-07-26 20:09
Closing as a duplicate of #283

**Closed by tuxor1337** 2021-07-26 20:09 UTC
