### ISSUE TITLE
[multi-monitor] Bar shows at the bottom of the top monitor

### ISSUE THREAD

**Issue by Rphad** [mlutfy/hidetopbar#233] opened 2020-06-22 13:29 UTC
I'm experiencing this weird bug, and it is rather annoying. I have a setup where (primary) monitor A is below monitor B. Sometimes (I reckon it is wen I'm working on mon A), the bar appears at the bottom of mon B. In the settings, everything is disabled. How can I patch this ? 
In the following screenshot, the red line marks the boundary between the two 1080p screens.
![dual_screen](https://user-images.githubusercontent.com/49572419/85293023-0b429700-b49d-11ea-877e-d1e8b0eb0ed0.png)

**Comment by tuxor1337** [comment] 2020-06-22 19:04
Duplicate of #178 and/or #153.

**Closed by tuxor1337** 2020-06-22 19:04 UTC
Labels: multi-monitor
