### ISSUE TITLE
Intellihide doesn't react when half tiling

### ISSUE THREAD

**Issue by FMuro** [mlutfy/hidetopbar#117] opened 2016-11-27 01:53 UTC
Hi. First of all, thanks for this amazing extension. I've noticed that, with intellihide, when I snap a window to the left or right side of the screen, the top bar stays there. I'm on fedora 25 (wayland).

**Comment by tuxor1337** [comment] 2016-11-27 10:02
This issue seems to be related to GNOME 3.22 and/or Wayland. It does not occur with GNOME 3.20. As soon as I'm on 3.22, I will probably look into this again.

**Comment by FMuro** [comment] 2016-11-27 12:46
Great, thanks! The positive side is that the corner is more reactive in hidden mode.

**Comment by FMuro** [comment] 2016-11-27 12:48
Sorry, I closed it by mistake.

**Comment by tuxor1337** [comment] 2016-11-27 13:16
I now had an opportunity to test on GNOME 3.22 and I was not able to reproduce this issue. Would you please give a list of all installed extensions and specify your hide-top-bar-settings (e.g. by screenshot of preferences window)?

**Comment by FMuro** [comment] 2016-11-28 13:14
No other extensions. This bug must have to do with wayland. In the attached ZIP you have a short screen cast  showing the behavior with Brasero (wayland) and Firefox (Xwayland). Firefox behaves well.
[Screencast from 28-11-16 14:08:43.zip](https://github.com/mlutfy/hidetopbar/files/616328/Screencast.from.28-11-16.14.08.43.zip)

**Comment by tuxor1337** [comment] 2016-11-28 18:52
Still, I can't reproduce this, including using Brasero. Would you specify your hide-top-bar-settings (e.g. by screenshot of preferences window), please?

**Comment by FMuro** [comment] 2016-11-29 10:42
Maybe you can replace Brasero with Gedit, or the terminal, or any other gnome 3.22 core app which is known to be running under wayland in your distro. Brasero wasn't really a good choice, I just happened to have it open.

![screenshot from 2016-11-29 11-27-14](https://cloud.githubusercontent.com/assets/17141976/20706655/9fffe086-b628-11e6-96c9-900705d29d4f.png)

**Comment by tuxor1337** [comment] 2016-11-29 17:19
Okay, I was now able to reproduce this. It's probably not even Wayland-related. It's simply a problem in intellihide (it does not notice maximize events) and would probably be fixed by upgrading intellihide to the most recent version from the project https://github.com/micheleg/dash-to-dock. This would mean dropping support for GNOME 3.16. But probably we can do this...

**Comment by FMuro** [comment] 2016-11-29 19:14
Ohhh, that would be great, thanks!

**Closed** 2016-12-01 22:29 UTC
Labels: bug

**Comment by tuxor1337** [comment] 2016-12-01 22:30
Would you give the current Github version a try, please? If it's okay, I will upload it on extensions.gnome.org.

**Comment by FMuro** [comment] 2016-12-02 08:56
Confirmed, it works! Thanks a lot for fixing this.
