### ISSUE TITLE
Top bar conflicts with dock and workspace

### ISSUE THREAD

**Issue by douglasilvadev** [mlutfy/hidetopbar#300] opened 2021-09-13 14:06 UTC
Hi there!

I'd like to report that this seems to be a bug when 'Hide Top Bar' bypasses the Ubuntu dock position absolutely overwriting its orientation and changing workspace elements position too. When I disable this extension then everything goes back right. It would be interesting if when the Top Bar comes back appear then the dock and workspace were oriented according to Top Bar position just like in the default version. Thanks!

![Screen1](https://i.ibb.co/zHPb9dn/Screenshot-from-2021-09-13-10-25-18.png)
![Screen2](https://i.ibb.co/M9k3GYD/Screenshot-from-2021-09-13-10-25-50.png)
![Screen3](https://i.ibb.co/mrK6K4Z/Screenshot-from-2021-09-13-10-26-49.png)
![Screen4](https://i.ibb.co/4T3hmJh/Screenshot-from-2021-09-13-10-26-52.png)

OS: Ubuntu 20.04 LTS
WM: Gnome 3.36.8 Wayland

**Comment by tuxor1337** [comment] 2021-09-13 17:24
Duplicate of #149 and #190

**Closed by tuxor1337** 2021-09-13 17:24 UTC
