### ISSUE TITLE
Error for lattest update

### ISSUE THREAD

**Issue by ruben966** [mlutfy/hidetopbar#303] opened 2021-09-13 22:13 UTC
Hello, I just updated the extension to the newest version and now the extension doesn't work anymore, it shows "error" instead of the on/off switch. (see photo). Maybe there is something wrong with the update?
![Screenshot-20210914000316-1116x172](https://user-images.githubusercontent.com/74718120/133162751-11518724-d095-4ad2-8f53-953f8ed9999d.png)

**Comment by orpheustaken** [comment] 2021-09-13 22:28
Download and extract this commit into your downloads folder:
https://github.com/mlutfy/hidetopbar/tree/285d953c2bb0123cfddde37a877e7ae09c88fb2e

```bash
cd ~/.local/share/gnome-shell/extensions/
rm -rf hidetopbar@mathieu.bidon.ca
mv ~/Downloads/hidetopbar-285d953c2bb0123cfddde37a877e7ae09c88fb2e  .
mv hidetopbar-285d953c2bb0123cfddde37a877e7ae09c88fb2e/ hidetopbar@mathieu.bidon.ca/
cd hidetopbar@mathieu.bidon.ca/
make
```
Reboot the system and everything will probably be working again.

PS: If you find any issue while running make, just install whatever command it complains about.

**Comment by tuxor1337** [comment] 2021-09-13 22:35
Most probably a duplicate of #301 which is already fixed.

The fixed version is currently under review and the broken version is already deactivated on extensions.gnome.org. So, if you re-install, you will either be back on the previous version, or you will get the fixed version (if it has passed reviewed by the time you read this).

**Closed by tuxor1337** 2021-09-13 22:35 UTC
