### ISSUE TITLE
Accessing Extension Options Throws Err

### ISSUE THREAD

**Issue by SamKomesarook** [mlutfy/hidetopbar#338] opened 2022-01-30 09:42 UTC
Running extension version 102 with gnome version 40.4.0 on PopOS 21.10

Works normally, except for when I try to access the extension options through the Pop Extension app, and I receive this stacktrace: 

The settings of extension hidetopbar@mathieu.bidon.ca had an error:
```
GLib.FileError: Failed to open file “/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/Settings-40.ui”: No such file or directory
```

Stack trace:
```
buildPrefsWidget@/usr/share/gnome-shell/extensions/hidetopbar@mathieu.bidon.ca/prefs.js:44:13
_init@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:209:40
OpenExtensionPrefsAsync/<@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:122:28
asyncCallback@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:115:22
run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:177:20
main@resource:///org/gnome/Shell/Extensions/js/main.js:19:13
run@resource:///org/gnome/gjs/modules/script/package.js:206:19
start@resource:///org/gnome/gjs/modules/script/package.js:190:8
@/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17
```

Really appreciate the work on this extension!

**Comment by tuxor1337** [comment] 2022-01-30 09:53
Closing as a duplicate of #320

**Closed by tuxor1337** 2022-01-30 09:53 UTC
