### ISSUE TITLE
Compatibility with Dash-to-dock

### ISSUE THREAD

**Issue by zapashcanon** [mlutfy/hidetopbar#96] opened 2016-04-04 11:16 UTC
Hi,

Please see: https://github.com/micheleg/dash-to-dock/issues/298

I think there's some kind of conflict between Hide top bar and Dash-to-dock.

To reproduce the bug, just launch firefox, watch a video in fullscreen (1 min. should be enough), exit fullscreen. Then, top bar won't reappear when mouse is at the top of screen, and so does the dock with the bottom of the screen.

(It's maybe linked to #51 ; I just saw..)

**Comment by FMuro** [comment] 2016-04-29 14:47
I can confirm this.

**Comment by BunnyApocalypse** [comment] 2016-05-23 23:05
Bump

**Comment by brandleesee** [comment] 2016-08-26 08:36
I can confirm this as well on GNOME Shell 3.18.5

**Comment by jvault** [comment] 2016-09-16 03:49
Have a peculiar bug with html5 players on Chrome too: after closing the full-screen by first time, browser windows stay fixed on stand out.

**Comment by sonejizrelax** [comment] 2017-08-02 19:20
This is very similar to the issue "not work well with google chrome browser" i think it may be the same bug

**Comment by jvault** [comment] 2017-08-06 03:12
@sonejizrelax Yes, It's the same nasty bug, but the cause is in dash-to-dock not in the browsers.

Enable the dock in full-screen mode can help, but the problem remains. Drag/Unhook the player tab and after close, so far the only way to work.

**Comment by zapashcanon** [comment] 2017-09-27 18:36
It seems that the issue is fixed for me, didn't see this behavior for a long time. Can someone confirm ?

**Comment by jvault** [comment] 2017-09-28 19:28
I confirm, apparently the problem has been fixed. I just tried a couple of different browsers and settings for dash-to-dock and it seems to works fine. I also noticed that a while ago, but as I try to avoid full-video can't identify exactly when (I suspect last update of gnome: 3.24.3).

**Closed** 2017-11-19 17:49 UTC
Labels: compatibility, unconfirmed
