### ISSUE TITLE
Ubuntu Dock overlapping top bar

### ISSUE THREAD

**Issue by TIIUNDER** [mlutfy/hidetopbar#243] opened 2020-07-14 20:25 UTC
After enabling this plugin, the top bar shows behind the Ubuntu Dock.

![Tooltip_2020-07-14_22:24:16](https://user-images.githubusercontent.com/1225378/87472847-e6b38800-c620-11ea-930e-c4cd63118e91.png)

**Comment by TIIUNDER** [comment] 2020-07-14 20:35
FYI, I created a workaround. A small bash script disables and enables the extension on login. This way the top bar is overlapping the dock like it should.

**Comment by tuxor1337** [comment] 2020-07-14 20:35
Closing as duplicate of https://github.com/mlutfy/hidetopbar/issues/149

**Closed by tuxor1337** 2020-07-14 20:35 UTC
