### ISSUE TITLE
Notifications are cut off by top bar

### ISSUE THREAD

**Issue by JamesSwift** [mlutfy/hidetopbar#220] opened 2020-05-19 11:12 UTC
If I have the bar set to show when no window is full screen, when a notification comes in, the top of it is cut off by the top bar.

**Comment by tuxor1337** [comment] 2020-05-19 16:26
Duplicate of #198 which is already fixed by #219. Fixed version is in review on extensions.gnome.org and will be officially available soon.

**Closed by tuxor1337** 2020-05-19 16:26 UTC
