### ISSUE TITLE
Activity search height is too small after installing the extension

### ISSUE THREAD

**Issue by guivc** [mlutfy/hidetopbar#371] opened 2022-07-09 18:17 UTC
You may see that "type to search" is too small and with the extension enabled I can't even see what I'm typing. Any tip to solve it?

![Screenshot from 2022-07-09 15-05-12](https://user-images.githubusercontent.com/25881395/178117991-1a577684-e624-422b-8ba2-8b7784ccda26.png)

With it disabled it backs to normal:

![Screenshot from 2022-07-09 15-15-44](https://user-images.githubusercontent.com/25881395/178118104-79c67d0d-d58a-4be7-8e33-65535abe1468.png)

**Comment by tuxor1337** [comment] 2022-07-24 17:59
Closing as duplicate of #321

**Closed by tuxor1337** 2022-07-24 17:59 UTC
